### ISSUE TITLE
Docs needed: oscillator and gain

### ISSUE THREAD

**Issue by azureus89** [224-1/psilib-html5-theremin#16]

**Comment by azureus89** [comment]
specifically what is (. something) and (.- something) and set! amd (js/something) and (something.)

**Comment by sahabaishakhi** [comment]
an oscillator is a source which is defined inside the audio context. samples of sound intensities can be generated by it. an oscillator node can be created by `context.createOscillator()` **method** in javascript where context is an audio context **object**, whose equivalent clojurescript syntax is `(defonce osc (.createOscillator context))`. similarly `context.createGain()` method in javascript can be written in clojurescript in the same manner. a gain control is used to modify the amplitude by having the GainNode connect to the oscillator to set the parameter value to get the modified amplitude as parameter value times the default amplitude. 
in order to initialise the oscillator and gain, we need to obtain the value of the atom by dereferencing inst-state and setting the `:osc` value to the oscillator node's shape of waveform obtained via its `type` **property**. in js it is obtained by `OscillatorNode.type = type` and in cljs the code is `(set! (.-type osc) (:osc @inst-state))`. the gain value of the GainNode is set by obtaining `:gain` from the derefed atom. in js code `gainNode.gain.value = 0.042` can be used to set the value and `(set! (.-value (.-gain amp)) (:gain @inst-state))` in cljs where `.-gain` and `.-value` are used to obtain property of the node.

**Comment by sahabaishakhi** [comment]
in clojurescript (js/something) is used to access any top level namespace such as `js/window` or `js/document` in browser namespace. `. something something` could be used as a way to avoid too much nesting, example of which can be seen in the oscillator start code ` (. osc start 0)`. `.-something` implements a property accessor. I haven't seen `something.` in cljs yet but it is the syntax in javascript

**Comment by kattakavya** [comment]
Oscillator produces a periodic wave form like sine wave. The syntax to create Oscillator is 
(defonce osc  (.createOscillator context)) 
Were ,defonce - is used to represent the var,which can be used ones.
	  context - is used to create an object.
For Sine wave the  oscillator produces the values between 1 and -1, This peak amplitude '1'  is constant and which cannot be changed.We are using separate gain controller to modify the amplifier .here we are connecting  an oscillator node to a gain node to get the modified amplitude.
The audio signal is generated by the oscillator and flows through the gain before reaching the destination. The gain alters the signal by having its amplitude.
