### ISSUE TITLE
Docs needed detune. Why use it?

### ISSUE THREAD

**Issue by azureus89** [224-1/psilib-html5-theremin#17]

**Comment by sahabaishakhi** [comment]
detune linearizes the frequency domain and its unit is meansure in cents where each octave is equal to 1200 cents. every semitone consists of 100 cents. the + and - signs before a specified number in web audio API makes you move up and down the octave, respectively. in the atom detune's value is set as 100 which makes the signal's pitch move one semitone up the current pitch

**Comment by kattakavya** [comment]
**Detune** it a  parameter measure in cents which modulates  the speed at which is rendered the audio stream.  by detuning the oscillators  makes them run slightly faster or slower and go out of phase with relation to each other, making for a more organic, dynamic, thicker sound. or just something horribly out of tune, depending on how much we do it.Detune can often gives a  less static sound because it detunes one osc down a few cents and the other a few cents up which causes beating  it is .A detuning value (in cents) which will offset the frequency by the given amount by default is 0.

**Comment by azureus89** [comment]
Nothing in life sounds perfect, and the human ear can detect it, things sound more organic when they are slightly imperfect, thats what detune accomplishes.
