### ISSUE TITLE
Why does the audio not start automatically?

### ISSUE THREAD

**Issue by azureus89** [224-1/psilib-html5-theremin#21]

**Comment by ParikshithMohan** [comment]
It starts for me. If I run just your boilerplate, its automatically playing the sound. Using chrome.

**Comment by kattakavya** [comment]
Because we are creating a button ,when we clicks it goes to audio-button function which contains the resume object. Resume method is the  time in seconds of the sample frame which immediately follows the last sample-frame in the block of audio which is most recently processed, as it takes the value '0' and process to play the audio.if we are not creating the button manually as **html5** audio is not supported by the chrome and it plays automatically if we click anywhere in the page  and refresh it

**Comment by azureus89** [comment]
@ParikshithMohan you're a cool guy. But its an issue if it happens even once on any behviour because then its not consistent and we can't depend on it. @kattakavya even I don't know what that means!

Haven't looked up the documentation on audio context in that level of detail, probably not even required for what we are trying to do .. audio context is basically an interface to the computers sound system ... only when you create an audio context can the browser use the computer sound system.

Audio does not start automatically because chrome needs the user to show that they WANT the audio on that page to start, otherwise it could create a problem of things playing in the background without the user being able to control it. Sample frame etc does not come into it. resume object etc is not related to the question, just wanted to know if we are on the same page on why the audio does not start automatically. The user needs to turn on the sound system in some way. Chrome does not allow a webpage to open with the sound system turned out automatically.

@ParikshithMohan remove flags from your system so that you are using a browser that is as close as possible to the normal user.

**Comment by azureus89** [comment]
Read receipts:
[ ] Baishakhi
[ ] Parikshith
[ ] Kavya

**Comment by azureus89** [comment]
@sahabaishakhi confirm, so I can close this

**Comment by sahabaishakhi** [comment]
Will do in sometime. No electricity, can't check the box.
