### ISSUE TITLE
What is gdom and need documentation  for multiply,mount functions

### ISSUE THREAD

**Issue by kattakavya** [224-1/psilib-html5-theremin#3]

**Comment by sahabaishakhi** [comment]
https://google.github.io/closure-library/api/goog.dom.html
upon passing the ID of an element in DOM, it returns the element.
according to the documentation of render-component in reagent library, it takes two arguments..one is a hiccup vector and the second is and the second is the DOM node.. should this be added in the comments?

**Comment by kattakavya** [comment]
why the multiply function has written?

**Comment by azureus89** [comment]
gdom is needed for reagent to work it uses googles closure library to create html components with hiccup and link them actively with javascript.

And multiply is written for testing. There is a test that runs that checks if multiply is working, if that test fails then you know that core clojurescript library itself has failed to load. It is not per se required as the project becomes larger, it will become obvious through other tests that we write whether basic library functions are working or not. For now you can keep it there.

**Comment by azureus89** [comment]
Mount is the name you are giving the function that calls reagent's render component function. Reagent binds html and javascript together to make it reactive so that html objects automatically re-render when the underlying data changes, this is why you can't just put the hello world html into the page using hiccups html5 function -- you will have to go through a lot of trouble after that linking the javscript to it so that it re-renders automatically when values change, reagent takes care of this for you when you use the render compoent function to create a reagent object. 

In the mount app element function you are calling the mount function which creates this enhanced html + js object and then writing it into el which is assigned to get-app-element.

Get app element function if you look above uses gdom to target the element in the html code with the id app. You dont have to create this div because if you check in the resources folder, index.html is created manually by lein with an empty div with id "app".

gdom is used by get-app-element to target this div.
Then render-component is used by mount function to create the hello-world object as a "reactive" component ie. it reacts automatically to changes in its values - you saw this when you tried out the cljs-boilerplate.
Then the mount-app-element function calls get-app-element which remembers the location of the div with id "app" and then it "mounts" hello worl into that div using the mount function which calls render-component.

**Comment by azureus89** [comment]
@kattakavya let me know if you've understood this or need a better explanation so I can try again or close this issue

**Comment by azureus89** [comment]
Closing this issue, as no additional questions recieved
